[package]
name = "oraiswap"
version = "1.0.0"
authors = ["Oraichain Labs","Terraform Labs, PTE."]
edition = "2021"
description = "Common oraiswap types used in different Oraichain Labs contracts like oraiDEX, IBC Wasm"
license = "MIT"
repository = "https://github.com/oraichain/oraiswap"
homepage = "https://orai.io"
documentation = "https://docs.orai.io"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "1.0.1" }
cosmwasm-storage = { version = "1.1.9" }
cosmwasm-std = { version = "1.1.9" }
thiserror = { version = "1.0.23" }
# using cw20-base contract as library
cw20-base = { version = "1.0.1", features = ["library"] }
cosmwasm-schema = "1.1.9"
schemars = "0.8.3"
protobuf = { version = "3.2.0", features = ["with-bytes"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# this import is for testing library
cw-multi-test = "0.16.2"



